server:
  port: 8080
  servlet:
    context-path: /
    
# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  
# Server configuration
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 0
  
  # Auto-configuration settings
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.couchbase.CouchbaseDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

# Camel configuration
camel:
  springboot:
    main-run-controller: false  # Disable Camel auto-startup
  servlet:
    mapping:
      context-path: /camel/*
  component:
    servlet:
      enabled: false  # Disable Camel servlet by default
  file-watch:
    enabled: false    # Disable file watch by default
    fileHasher: TRUE
    concurrentConsumers: 4
    pollThreads: 4
    queueSize: 1000

# File watch configuration for SWIFT MT files
file:
  watch:
    directory: ${FILE_WATCH_DIRECTORY:${java.io.tmpdir}/swift-inbox}
    patterns: "*.txt,*.fin,*.mt*"

# Kafka topics (default values, can be overridden)
kafka:
  topics:
    mt-raw: mt.raw
    mt-valid: mt.valid
    mt-invalid: mt.invalid
    mx-out: mx.out

# WebSocket configuration
websocket:
  enabled: false  # Disable WebSocket by default
  endpoint: /ws/messages
  app-prefix: /app
  topic: /topic/status
  destination-prefix: /topic

# Local development profile settings
---
spring:
  config.activate.on-profile: local
  jms:
    listener:
      auto-startup: false  # Disable JMS listener for local development
  kafka:
    enabled: false  # Disable Kafka for local development
  activemq:
    in-memory: false  # Don't use in-memory broker
  
# Logging for local development
logging:
  level:
    org:
      springframework: INFO
      apache: WARN
    com:
      iso20022: DEBUG
