version: '3.8'

services:
  # Message Broker
  activemq:
    image: rmohr/activemq:5.15.9
    ports:
      - "61616:61616"  # OpenWire
      - "5672:5672"    # AMQP
      - "1883:1883"    # MQTT
      - "8161:8161"    # Web Console
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
      - ACTIVEMQ_JMX=yes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8161"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kafka and Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"

  # CouchDB
  couchdb:
    image: couchdb:3.3.1
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Ingest Service
  ingest-service:
    build: ./ingest-service
    ports:
      - "8080:8080"
    depends_on:
      kafka:
        condition: service_healthy
      activemq:
        condition: service_healthy
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq:61616
      - SPRING_DATA_COUCHDB_HOST=couchdb
      - SPRING_DATA_COUCHDB_USERNAME=admin
      - SPRING_DATA_COUCHDB_PASSWORD=password
      - SPRING_DATA_COUCHDB_SSL_ENABLED=false
    volumes:
      - ./ingest-service/logs:/app/logs
      - ./ingest-service/config:/app/config
      - swift-inbox:/home/user/swift-inbox

  # Validation Service
  validation-service:
    build: ./validation-service
    ports:
      - "8081:8080"
    depends_on:
      - kafka
      - couchdb
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_DATA_COUCHDB_HOST=couchdb
      - SPRING_DATA_COUCHDB_USERNAME=admin
      - SPRING_DATA_COUCHDB_PASSWORD=password
      - SPRING_DATA_COUCHDB_SSL_ENABLED=false

  # Transform Service
  transform-service:
    build: ./transform-service
    ports:
      - "8082:8080"
    depends_on:
      - kafka
      - couchdb
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_DATA_COUCHDB_HOST=couchdb
      - SPRING_DATA_COUCHDB_USERNAME=admin
      - SPRING_DATA_COUCHDB_PASSWORD=password
      - SPRING_DATA_COUCHDB_SSL_ENABLED=false

  # Router Service
  router-service:
    build: ./router-service
    ports:
      - "8083:8080"
    depends_on:
      - kafka
      - couchdb
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_DATA_COUCHDB_HOST=couchdb
      - SPRING_DATA_COUCHDB_USERNAME=admin
      - SPRING_DATA_COUCHDB_PASSWORD=password
      - SPRING_DATA_COUCHDB_SSL_ENABLED=false

  # UI Service
  ui:
    build: ./ui
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
      - REACT_APP_WS_URL=ws://localhost:8080/ws
    depends_on:
      - ingest-service
    volumes:
      - ./ui/src:/app/src
      - /app/node_modules

volumes:
  couchdb_data:
  swift-inbox:
