server:
  port: 8082

spring:
  application:
    name: transform-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: transform-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  couchdb:
    host: localhost
    port: 5984
    username: admin
    password: password
    database: swift_mx_audit
    ssl-enabled: false

# Kafka topics
kafka:
  topics:
    mt-valid: mt.valid
    mx-out: mx.out

# Transformation configuration
transform:
  mapping:
    mt103: "pacs.008.001.08"  # MT103 -> pacs.008.001.08 (FIToFICustomerCreditTransferV08)
    mt202: "pacs.009.001.08"  # MT202 -> pacs.009.001.08 (FIToFICustomerCreditTransferV08)
    # Add more mappings as needed
